default: &default
  adapter:  postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials[Rails.env.to_sym][:database][:username] rescue nil %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:database][:password] rescue nil %>
  host: <%= Rails.application.credentials[Rails.env.to_sym][:database][:host] rescue nil %>
development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
